- name: P. L. Lim
  email: 2090236+pllim@users.noreply.github.com
  num_commits: 1
  first_commit: 2019-05-05 09:56:53
  github: pllim
- name: Julien Schueller
  email: schueller@phimeca.com
  num_commits: 1
  first_commit: 2019-05-30 11:40:35
  github: jschueller
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 128
  first_commit: 2019-04-05 16:53:05
- name: Isaiah Norton
  email: isaiah.norton@gmail.com
  num_commits: 5
  first_commit: 2019-08-09 09:21:03
  github: ihnorton
- name: Marcelo Duarte Trevisani
  email: marceloduartetrevisani@gmail.com
  alternate_emails:
  - marcelotrevisani@users.noreply.github.com
  num_commits: 23
  first_commit: 2019-09-04 04:28:53
  github: marcelotrevisani
