variables:
  deps.space: 'conda requests xonsh lazyasd tqdm ruamel.yaml pytest pytest-flake8 pytest-timeout'
  deps.comma: 'conda,requests,xonsh,lazyasd,tqdm,ruamel.yaml,pytest,pytest-flake8,pytest-timeout'

jobs:
- job: 'conda-press windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      python36:
        python.version: '3.6'
      python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - template: azure-steps.yml
- job: 'conda-press mac'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      python36:
        python.version: '3.6'
      python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - template: azure-steps.yml
- job: 'conda-press linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      python36:
        python.version: '3.6'
      python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - template: azure-steps.yml
